#!/bin/zsh

# ===============================================================================================
# Misc. functions
# ===============================================================================================

function tunnlr() {
  if [[ $1 ]]; then PORT=$1 else PORT=3001 fi
  echo "codyss-t.tunnlr.com"
  ssh  -nNt -g -R :12821:192.168.99.100:$PORT tunnlr3599@ssh1.tunnlr.com
}

function des_tunnlr() {
  if [[ $1 ]]; then PORT=$1 else PORT=3002 fi
  echo "codyssdesigner-t.tunnlr.com"
  ssh  -nNt -g -R :13218:0.0.0.0:$PORT tunnlr4123@ssh1.tunnlr.com
}

function lscolors(){
  for i in {0..255} ; do
    printf "\x1b[38;5;${i}mcolour${i}\n"
  done
}

function work(){
  docker-machine start;
  tmator work || tmux attach -t work
}

